language: node_js

cache: npm

git:
  depth: 1

jobs:
  include:
    - stage: Test
      node_job: "10.16.0"
      before_install: npm install -g npm@latest
      install: npm install
      script:
        - npm test