language: node_js

cache: npm

git:
  depth: 1

jobs:
  include:
    - stage: Test
      node_js: "10"
      before_install: npm install -g npm@latest
      install: npm install
      script:
        - npm test
    - stage: Code Coverage
      node_js: "10"
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage